name: CI
on: [push]
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: sudo apt install gettext
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --silent
      - name: Run jest tests
        run: yarn test
  cypress:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: sudo apt install gettext
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        env:
          CYPRESS_DHIS2_AUTH: ${{ secrets.CYPRESS_DHIS2_AUTH }}
          CYPRESS_ROOT_URL: http://localhost:8081
          CYPRESS_EXTERNAL_API: http://ec2-54-195-131-72.eu-west-1.compute.amazonaws.com
          REACT_APP_DHIS2_BASE_URL: http://ec2-54-195-131-72.eu-west-1.compute.amazonaws.com 
          NODE_ENV: development
        with:
          browser: firefox
          headless: true
          install-command: yarn install --frozen-lockfile --silent
          start: yarn start
          wait-on: 'http://localhost:8081'

